### ISSUE TITLE
Why list of available commands seems volatile?

### ISSUE THREAD

**Issue by mloskot** [sasq64/autotidy#5]
From time to time, some commands are not listed in subsequent refactoring steps, e.g. `[a]pply` below

![image](https://user-images.githubusercontent.com/80741/50997573-36455f00-1525-11e9-8d9c-1ea1b0523f92.png)

What is the reason? I couldn't figure out the pattern (not looked at the code yet, sorry).

**Comment by sasq64** [comment]
Simple, [a]pply is only available when there is a fix available.

**Comment by mloskot** [comment]
At first, the behaviour was confusing. It makes sense now. Thanks
