### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by afnanenayet** [sasq64/autotidy#8]
I was wondering if there is a license for this project that I missed. If not, is there any chance you could add one? It's useful to have licenses available esp if people want to use a tool in a corporate shop.

**Comment by sasq64** [comment]
Good point, I added the an MIT license.

**Comment by sasq64** [comment]
But is it common to inform about the license of external code in the top level directory also ?

**Comment by afnanenayet** [comment]
I think you're fine, unless the licenses specifically require it, but I don't think you're using any AGPL code so you should be good :)
